---
- name: Scripts | Setup Scripts Directory | template
  file:
    path: "{{ bin_directory }}"
    state: directory

- name: Scripts | Copies Scripts | template
  template:
    src: '{{ item.src }}'
    dest: "{{ bin_directory }}/{{ item.path  | regex_replace('\\.j2$', '') }}"
  with_filetree: '../templates'
  when: item.state == 'file'

- name: Scripts | Change Script Permissions
  file:
    path: "{{ bin_directory }}"
    mode: +x
    state: directory
    recurse: yes
